random_state: 123
splitting:
  test_size: 0.2
  target_column: "purchase_price"
  columns_to_drop: ["house_id"]
processing:
  encoding:
    catboost: ["city", "zip_code", "address"]
    one_hot: ["house_type", "sales_type", "area", "region"]