random_state: 123
cv_folds: 5 

splitting:
  test_size: 0.2
  target_column: "purchase_price"

quarter_column: "quarter"
date_column: "date"
categorical_columns: 
  - city
exclude_columns: ["yield_on_mortgage_credit_bonds%", "dk_ann_infl_rate%"]
continuous_imputation_params: 
  exclude_cols: 
    - "yield_on_mortgage_credit_bonds%"
    - "dk_ann_infl_rate%"
  target_col: 
    - "yield_on_mortgage_credit_bonds%"
    - "dk_ann_infl_rate%"
columns_to_drop: 
  - "house_id"
  - "address"
  - "day"
  - "zip_code"
encoding:
  catboost: "city"
  one_hot: ["house_type", "sales_type", "area", "region", "quarter", "month"]

xgboost_model:
  param_grid:
    max_depth: "randint(3, 15)"
    learning_rate: "uniform(0.01, 0.3)"
    n_estimators: "randint(50, 500)"
    gamma: "uniform(0, 1)"
    subsample: "uniform(0.5, 0.5)"
    colsample_bytree: "uniform(0.5, 0.5)"

lightgbm_model:
  param_grid:
    num_leaves: "randint(20, 150)"
    learning_rate: "uniform(0.01, 0.3)"
    n_estimators: "randint(50, 500)"
    min_child_samples: "randint(5, 100)"
    subsample: "uniform(0.5, 0.5)"
    colsample_bytree: "uniform(0.5, 0.5)"

linear_regression_model:
  param_grid:
    fit_intercept: [True, False]
    positive: [True, False]
model_names:
  lightgbm: "LightGBM"
  xgboost: "XGBoost"
  linear_regression: "Linear Regression"
  catboost: "CatBoost"

catboost_model:
  param_grid:
    iterations: "randint(100, 1000)"              # Integer values between 100 and 1000
    learning_rate: "uniform(0.01, 0.3)"        # Continuous values between 0.01 and 0.31
    depth: "randint(4, 10)"                      # Integer values between 4 and 10
    l2_leaf_reg: "uniform(1, 10)"           # Continuous values between 1 and 11
    bagging_temperature: "uniform(0, 1)"        # Continuous values between 0 and 1

